### ISSUE TITLE
mischelper not compatible with R 3.5.1

### ISSUE THREAD

**Issue by jonathanowitz** [dracodoc/mischelper#1]
Hello, the most recent version of R does not support this. Any plans to update?

**Comment by dracodoc** [comment]
I didn't found any problem with R 3.5.1 in windows and Mac. What's the specific problem you met?

With R 3.5, all user packages need to be reinstalled. It could be your packages are not upgraded before installing `mischelper`. You can use RStudio's `upgrade` feature in package pane to upgrade all user packages if needed.

**Comment by jonathanowitz** [comment]
My mistake - I was trying `install.packages` instead of `devtools::install_github`.
