### ISSUE TITLE
Clarify licence

### ISSUE THREAD

**Issue by francisbarton** [dracodoc/mischelper#2]
Hi there

I'd like to "borrow" a few of your functions from `misc.R` - they look very useful. I'd like to add them to my own package of useful functions.
Your LICENSE statement just says you have copyright, and there's no further licensing information. Are you happy for me to copy some of your code, with attribution?

**Comment by dracodoc** [comment]
Sure, you can use them without any restriction except attribution.

I tried to choose a license in beginning but got confused on several options so didn't make a decision.

**Comment by francisbarton** [comment]
Thank you!
